export const UNUSED_VARS_OPTIONS = {
  args: 'after-used',
  argsIgnorePattern: '^_',
  varsIgnorePattern: '^_',
  caughtErrorsIgnorePattern: '^_',
  destructuredArrayIgnorePattern: '^_',
};

export const NODE_COMMON_RULES = {
  'no-console': ['warn', {allow: ['warn', 'error']}],
  'n/handle-callback-err': ['error', '^.*(e|E)rr'],
  'n/no-callback-literal': 'error',
  'n/no-path-concat': 'error',
  'n/no-process-exit': 'error',
  'n/callback-return': 'error',
  'n/global-require': 'error',
  'n/no-mixed-requires': 'error',
  'n/prefer-global/buffer': ['error', 'never'],
  'n/prefer-global/console': ['error', 'always'],
  'n/prefer-global/crypto': ['error', 'never'],
  'n/prefer-global/process': ['error', 'never'],
  'n/prefer-global/text-decoder': ['error', 'never'],
  'n/prefer-global/text-encoder': ['error', 'never'],
  'n/prefer-global/timers': ['error', 'never'],
  'n/prefer-global/url': ['error', 'never'],
  'n/prefer-global/url-search-params': ['error', 'never'],
  'n/prefer-promises/dns': 'error',
  'n/prefer-promises/fs': 'error',
  'n/no-process-env': ['warn', {allowedVariables: ['NODE_ENV']}],
  'n/no-sync': 'error',
  'n/no-new-require': 'error',
  'n/no-hide-core-modules': 'error',
  'n/no-missing-import': 'off',
  'n/no-unpublished-import': 'off',
  'n/no-unsupported-features/es-builtins': 'off',
  'n/no-unsupported-features/node-builtins': 'off',
  'unicorn/prevent-abbreviations': 'off',
  'unicorn/no-null': 'off',
  'unicorn/no-array-for-each': 'off',
  'unicorn/consistent-function-scoping': 'off',
  'unicorn/expiring-todo-comments': 'off',
  'unicorn/filename-case': 'off',
  'unicorn/numeric-separators-style': 'off',
};

export const REACT_COMMON_RULES = {
  '@eslint-react/jsx-no-useless-fragment': 'error',
  '@eslint-react/dom-no-missing-button-type': 'warn',
  '@eslint-react/dom-no-missing-iframe-sandbox': 'warn',
  '@eslint-react/dom-no-unsafe-target-blank': 'warn',
  '@eslint-react/no-misused-capture-owner-stack': 'error',
  '@eslint-react/no-unstable-context-value': 'warn',
  '@eslint-react/no-unstable-default-props': 'warn',
  '@stylistic/jsx-closing-bracket-location': ['error', 'tag-aligned'],
  '@stylistic/jsx-closing-tag-location': 'error',
  '@stylistic/jsx-curly-newline': ['error', {multiline: 'consistent', singleline: 'consistent'}],
  '@stylistic/jsx-wrap-multilines': 'error',
  '@stylistic/jsx-curly-brace-presence': ['error', {props: 'never', children: 'never'}],
  '@stylistic/jsx-curly-spacing': ['error', {when: 'never'}],
  '@stylistic/jsx-equals-spacing': ['error', 'never'],
  '@stylistic/jsx-first-prop-new-line': ['error', 'multiline'],
  '@stylistic/jsx-pascal-case': 'error',
  '@stylistic/jsx-quotes': ['error', 'prefer-double'],
  '@stylistic/jsx-self-closing-comp': 'error',
  'check-file/filename-naming-convention': ['error', {
    '**/*.{js,ts}': 'KEBAB_CASE',
    '**/*.{jsx,tsx,vue}': 'PASCAL_CASE',
  }, {ignoreMiddleExtensions: true}],
};
